name: Deploy Kryptrix to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Update if you need newer features

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running basic unit tests..."
          python -m unittest discover -s tests

      - name: Deploy to Hugging Face
        run: |
          git remote add hf https://huggingface.co/spaces/1FahadShah/kryptrix
          git push hf main
        env:
          HF_TOKEN: ${{ secrets.KRYPTRIX_SPACE_REPO_SYNC }}
